name: mikes
favicon: null
layout_spectrum: 0.25057
typography_spectrum: 0.17335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#31393b'
    - '#bfbfbf'
    - '#959595'
    - '#f49d34'
  brandStrength: 0.5651446224655956
  lightness: 0.5609397017396986
  saturation: 0.6935417961794883
  rhythmicContrast: 0.45012700743973255
purpose: []
